name: cloche-enterprise
description: "Cloche Enterprise"
base-image: quay.io/centos-bootc/centos-bootc
image-version: stream10

modules:
  - type: containerfile
    snippets:
      - RUN dnf install -y epel-release && dnf config-manager --set-enabled crb
      - RUN useradd -m -G wheel -p '$6$CARQCg8vB3/aeGNE$UflWEmXw5MMr9Z0lG6OHudKXc.AYGFozzNIO0XwVxzDF2ppfBcPdlya0RT9zNWTU7wBMk/TfAPWSBs2DPtpwS1' user

#  - type: dnf
#    install:
#      packages:
        #- "@Workstation"
        #- gdm

  #- type: systemd
    #system:
      #enabled:
        #- gdm.service
        #- NetworkManager.service
