name: cloche-enterprise
description: "CentOS Stream 10 Enterprise Base"
base-image: quay.io/almalinuxorg/almalinux-bootc

image-version: stream10
#quay.io/centos-bootc/centos-bootc
modules:
  - type: containerfile
    snippets:
      - RUN dnf install -y epel-release && dnf config-manager --set-enabled crb

#  - type: dnf
#    install:
#      packages:
        #- "@Workstation"
        #- gdm

  #- type: systemd
    #system:
      #enabled:
        #- gdm.service
        #- NetworkManager.service
