name: cloche-enterprise
description: "Cloche Enterprise"
base-image: quay.io/centos-bootc/centos-bootc
image-version: stream10

modules:
  - type: containerfile
    snippets:
      - RUN dnf install -y epel-release && dnf config-manager --set-enabled crb

#  - type: dnf
#    install:
#      packages:
        #- "@Workstation"
        #- gdm

  #- type: systemd
    #system:
      #enabled:
        #- gdm.service
        #- NetworkManager.service
