name: Build Enterprise ISO
on:
  workflow_dispatch: #
jobs:
  generate-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Prepares directory
        run: mkdir -p ./output

      - name: Pull OCI image
        run: sudo podman pull ghcr.io/augustofmarques/cloche-enterprise:latest

      - name: Build ISO
        run: |
          sudo podman run \
            --rm \
            --privileged \
            --pull=newer \
            --security-opt label=type:unconfined_t \
            -v ${{ github.workspace }}/output:/output \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type anaconda-iso \
            ghcr.io/augustofmarques/cloche-enterprise:latest

      - name: Upload ISO
        uses: actions/upload-artifact@v7
        with:
          name: cloche-enterprise-iso
          path: ./output/*.iso
          retention-days: 3
